import { readFile } from 'node:fs/promises';
import { test } from '@e2e-dev/web';
import { expect } from 'e2e';

interface Corpus { checksum: string; ayahs: Array<{ words: string[] }>; codepoints: number[] }

test('D1 full legal corpus renders in UI and offline harness fonts', { timeout: 120000 }, async ({ app, browser }) => {
  const corpusPath = process.env.D1_QURAN_CORPUS;
  test.skip(!corpusPath, 'Opt-in: supply D1_QURAN_CORPUS generated by the pinned dry-run importer');
  if (!corpusPath) return;
  const corpus = JSON.parse(await readFile(corpusPath, 'utf8')) as Corpus;
  const words = [...new Set(corpus.ayahs.flatMap((ayah) => ayah.words))];
  const symbols = corpus.codepoints.map((point) => String.fromCodePoint(point)).join('');
  // Deterministic offline UI font fixture uses the exact bundled Amiri bytes.
  // Production CSS and rendering code are untouched.
  await browser.route('https://fonts.googleapis.com/**', async route => route.fulfill({
    status: 200, contentType: 'text/css', body: '@font-face{font-family:Amiri;src:url(http://127.0.0.1:4188/fonts/amiri.ttf);font-weight:400;font-style:normal;}',
  }));
  for (const target of ['/', '/render-harness.html']) {
    await app.open(target);
    const loadedFonts = await browser.evaluate(async (input: { symbols: string }) => {
      const fonts = await document.fonts.load('32px "Amiri"', input.symbols);
      return fonts.length;
    }, { symbols });
    expect(loadedFonts).toBeGreaterThan(0);
    let checked = 0;
    for (let offset = 0; offset < words.length; offset += 500) {
    const result = await browser.evaluate(async (input: { words: string[] }) => {
      const family = 'Amiri';
      const canvas = document.createElement('canvas');
      canvas.width = 1024; canvas.height = 80;
      const context = canvas.getContext('2d')!;
      context.font = `32px "${family}"`;
      context.direction = 'rtl';
      context.textAlign = 'right';
      const blankWords: string[] = [];
      for (const word of input.words) {
        context.clearRect(0, 0, canvas.width, canvas.height);
        context.fillText(word, 1000, 60);
        const width = Math.min(1024, Math.ceil(context.measureText(word).width) + 50);
        if (!context.getImageData(1024 - width, 0, width, canvas.height).data.some((value, index) => index % 4 === 3 && value > 0)) blankWords.push(word);
      }
      return { checked: input.words.length, blankWords };
    }, { words: words.slice(offset, offset + 500) });
    checked += result.checked;
    expect(result.blankWords).toEqual([]);
    }
    expect(checked).toBe(words.length);
    await browser.evaluate((input: { words: string[]; symbols: string }) => {
      // Visible proof sheet for all corpus symbols; only the test DOM changes.
      const proof = document.createElement('div');
      proof.style.cssText = 'position:fixed;inset:0;background:#fff;color:#111;z-index:999999;padding:30px;font:42px "Amiri";direction:rtl;overflow:auto';
      proof.textContent = `D1 — ${input.words.length} unique words checked\n` + Array.from(input.symbols).join('  ') + '\n' + input.words.slice(0, 40).join(' ');
      document.body.append(proof);
    }, { words, symbols });
    await app.screenshot(target === '/' ? 'd1-corpus-ui-symbols' : 'd1-corpus-render-harness-symbols');
  }
});
