import fs from 'fs';
import path from 'path';
import os from 'os';
import crypto from 'crypto';
import { spawn } from 'child_process';
import { RenderManifest } from '../models/renderManifest';
import { logger } from '../logger';
import { probeMediaFile, validateProbeAgainstSpec } from './mediaProbeService';
import { prepareAudioTrack, prepareBackgroundAsset, DeterministicRenderOptions, DeterministicRenderResult, extractAyahsAndWords } from './deterministicVideoRenderer';
import { getFfmpegBinary, getFfmpegPreset, getFfmpegResourceArgs, getFfmpegVideoEncoderArgs } from './ffmpegBinary';
import { renderFullFidelityVideo } from './browserCloudRenderer';

/**
 * Converts numbers to Arabic Eastern numerals (٠-٩)
 */
export function toArabicDigits(num: number | string): string {
  const arabicNums = ['٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'];
  return num.toString().split('').map((d) => arabicNums[parseInt(d, 10)] || d).join('');
}

/**
 * Formats seconds into ASS timestamp format: H:MM:SS.cs
 */
export function formatAssTimestamp(seconds: number): string {
  const clamped = Math.max(0, seconds);
  const h = Math.floor(clamped / 3600);
  const m = Math.floor((clamped % 3600) / 60);
  const s = Math.floor(clamped % 60);
  const cs = Math.floor((clamped % 1) * 100);
  return `${h}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}.${cs.toString().padStart(2, '0')}`;
}

/**
 * Converts CSS hex/rgb color to ASS BGR format (&HAABBGGRR)
 */
export function toAssColor(hex: string, alphaHex = '00'): string {
  let clean = hex.replace('#', '').trim();
  if (clean.length === 3) {
    clean = clean.split('').map((c) => c + c).join('');
  }
  if (clean.length >= 6) {
    const r = clean.slice(0, 2);
    const g = clean.slice(2, 4);
    const b = clean.slice(4, 6);
    // ASS uses &HAABBGGRR format
    return `&H${alphaHex}${b}${g}${r}&`;
  }
  return `&H${alphaHex}FFFFFF&`;
}

/**
 * Resolves ASS color & border codes for each glow style
 */
export function resolveAssGlowColors(glowStyle?: string): { color: string; border: string } {
  switch (glowStyle) {
    case 'emerald':
      return { color: '&H0078C850&', border: '&H00578B2E&' };
    case 'neon':
    case 'cyan':
      return { color: '&H00F8BD38&', border: '&H00C78402&' };
    case 'pure_white':
    case 'white':
      return { color: '&H00FFFFFF&', border: '&H00E0E0E0&' };
    case 'ruby':
      return { color: '&H007171F8&', border: '&H002626DC&' };
    case 'golden':
    default:
      return { color: '&H0037AFD4&', border: '&H00D4AF37&' };
  }
}

/**
 * Generates SubStation Alpha (.ass) subtitle file content for the Quran reel.
 * Implements:
 * 1. Exact Right-to-Left (RTL) Arabic typography
 * 2. High-precision word-by-word gold highlight
 * 3. Surah and Reciter header cards
 * 4. Ayah end rosette brackets ﴿١﴾
 */
export function generateQuranAssContent(manifest: RenderManifest, fontsDir?: string): string {
  const { width, height } = manifest.outputDimensions;
  const isPortrait = height >= width;

  // Responsive font scaling respecting user preferences
  const fontScale = (manifest.typography?.fontSize && manifest.typography.fontSize > 0)
    ? manifest.typography.fontSize / 28
    : 1.0;
  const baseFontSize = Math.round((isPortrait ? height * 0.038 : height * 0.055) * fontScale);
  const headerFontSize = Math.round(baseFontSize * 0.65);
  const reciterFontSize = Math.round(baseFontSize * 0.52);

  const fontName = (manifest.typography?.fontFamily && manifest.typography.fontFamily.toLowerCase().includes('noto'))
    ? 'Noto Naskh Arabic'
    : 'Amiri';
  const headerFont = 'Noto Naskh Arabic';

  // Primary text color respecting user customization
  const normalTextColor = manifest.typography?.textColor
    ? toAssColor(manifest.typography.textColor)
    : '&H00FFFFFF&';

  // Highlight glow color mapping
  const glowColors = resolveAssGlowColors(manifest.displaySettings?.glowStyle);
  const activeGoldColor = glowColors.color;
  const activeGlowBorder = glowColors.border;
  const shadowColor = '&H90000000&';
  const borderColor = '&H00000000&';

  const marginV = Math.round(height * (isPortrait ? 0.22 : 0.16));
  const marginLR = Math.round(width * 0.08);

  const lines: string[] = [
    '\uFEFF[Script Info]', // UTF-8 BOM
    '; Script generated by AyahX Native FFmpeg ASS Engine',
    'Title: Quran Reel',
    'ScriptType: v4.00+',
    'WrapStyle: 0',
    'ScaledBorderAndShadow: yes',
    'YCbCr Matrix: TV.709',
    `PlayResX: ${width}`,
    `PlayResY: ${height}`,
    '',
    '[V4+ Styles]',
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
    // Main Quran Ayah Style: Centered (Alignment 5 = Middle-Center or 2 = Bottom-Center)
    `Style: QuranMain,${fontName},${baseFontSize},${normalTextColor},${activeGoldColor},${borderColor},${shadowColor},-1,0,0,0,100,100,1,0,1,3.5,2.5,5,${marginLR},${marginLR},${marginV},1`,
    // Surah Header at Top (Alignment 8 = Top-Center)
    `Style: SurahTitle,${headerFont},${headerFontSize},${activeGoldColor},${normalTextColor},${borderColor},${shadowColor},-1,0,0,0,100,100,1,0,1,2.0,1.5,8,40,40,${Math.round(height * 0.08)},1`,
    // Reciter Name below Surah Header (Alignment 8)
    `Style: ReciterTitle,${headerFont},${reciterFontSize},&H00D0D0D0&,${normalTextColor},${borderColor},${shadowColor},0,0,0,0,100,100,0,0,1,1.5,1.0,8,40,40,${Math.round(height * 0.13)},1`,
    '',
    '[Events]',
    'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text',
  ];

  const totalDuration = manifest.audio.durationSeconds || 30;

  // 1. Top Header: Surah Name and Reciter Name
  if (manifest.displaySettings?.showSurahName) {
    const surahText = `سُورَةُ ${manifest.canonicalAyahRange.surahName.replace(/^سورة\s+/, '')}`;
    lines.push(`Dialogue: 0,0:00:00.00,${formatAssTimestamp(totalDuration)},SurahTitle,,0,0,0,,${surahText}`);
  }

  if (manifest.displaySettings?.showReciterName) {
    const reciterText = `تلاوة: ${manifest.reciter.name}`;
    lines.push(`Dialogue: 0,0:00:00.00,${formatAssTimestamp(totalDuration)},ReciterTitle,,0,0,0,,${reciterText}`);
  }

  // 2. Ayahs and Word Timings (if Ayah text is enabled)
  const showAyahText = manifest.displaySettings?.showAyahText !== false;
  const showAyahNumber = manifest.displaySettings?.showAyahNumber !== false;
  const doWordHighlight = manifest.displaySettings?.highlightStyle !== 'none';

  if (showAyahText) {
    const { ayahs, words } = extractAyahsAndWords(manifest);

    // Group words by verse
    const ayahWordGroups = new Map<number, typeof words>();
    for (const w of words) {
      const match = w.canonicalWordKey?.match(/^(\d+):(\d+):/);
      const ayahNum = match ? parseInt(match[2], 10) : ayahs[0]?.numberInSurah;
      if (!ayahWordGroups.has(ayahNum)) {
        ayahWordGroups.set(ayahNum, []);
      }
      ayahWordGroups.get(ayahNum)!.push(w);
    }

    // Compute timing ranges for each Ayah
    let previousEnd = 0;
    for (let i = 0; i < ayahs.length; i++) {
      const ayah = ayahs[i];
      const ayahWords = ayahWordGroups.get(ayah.numberInSurah) || [];
      
      let ayahStartSec = previousEnd;
      let ayahEndSec = totalDuration;

      if (ayahWords.length > 0) {
        const firstWordStart = ayahWords[0].startMs / 1000;
        const lastWordEnd = (ayahWords[ayahWords.length - 1].endMs ?? ayahWords[ayahWords.length - 1].startMs + 600) / 1000;
        ayahStartSec = Math.max(0, firstWordStart);
        ayahEndSec = Math.min(totalDuration, lastWordEnd + 0.8);
        // Give a clean transition boundary between ayahs
        if (i < ayahs.length - 1) {
          const nextAyahWords = ayahWordGroups.get(ayahs[i + 1].numberInSurah);
          if (nextAyahWords && nextAyahWords.length > 0) {
            ayahEndSec = Math.min(ayahEndSec, nextAyahWords[0].startMs / 1000);
          }
        }
      } else {
        // If words are not timestamped, divide total duration evenly
        const durationPerAyah = totalDuration / ayahs.length;
        ayahStartSec = i * durationPerAyah;
        ayahEndSec = (i + 1) * durationPerAyah;
      }

      previousEnd = ayahEndSec;

      const ayahBracket = showAyahNumber ? ` ﴿${toArabicDigits(ayah.numberInSurah)}﴾` : '';
      const fullTokens = ayahWords.length > 0 ? ayahWords.map((w) => w.displayToken) : ayah.text.split(/\s+/);

      if (ayahWords.length === 0 || !doWordHighlight) {
        // Display full verse cleanly without per-word jump
        const startStr = formatAssTimestamp(ayahStartSec);
        const endStr = formatAssTimestamp(ayahEndSec);
        lines.push(`Dialogue: 1,${startStr},${endStr},QuranMain,,0,0,0,,${ayah.text}${ayahBracket}`);
        continue;
      }

      // Pre-verse pause: Show entire verse with neutral text before first word activates
      if (ayahWords[0].startMs / 1000 > ayahStartSec + 0.05) {
        const startStr = formatAssTimestamp(ayahStartSec);
        const endStr = formatAssTimestamp(ayahWords[0].startMs / 1000);
        const fullText = fullTokens.join(' ') + ayahBracket;
        lines.push(`Dialogue: 1,${startStr},${endStr},QuranMain,,0,0,0,,${fullText}`);
      }

      // Word-by-word highlights
      for (let wIndex = 0; wIndex < ayahWords.length; wIndex++) {
        const word = ayahWords[wIndex];
        const wordStart = word.startMs / 1000;
        const nextWord = ayahWords[wIndex + 1];
        const wordEnd = nextWord ? nextWord.startMs / 1000 : Math.min(ayahEndSec, (word.endMs ?? word.startMs + 600) / 1000);

        if (wordEnd <= wordStart) continue;

        const startStr = formatAssTimestamp(wordStart);
        const endStr = formatAssTimestamp(wordEnd);

        // Build text with active word tagged with gold color
        const formattedParts: string[] = [];
        for (let k = 0; k < fullTokens.length; k++) {
          if (k === wIndex) {
            // Highlight active word with golden color and extra glow
            formattedParts.push(`{\\c${activeGoldColor}\\3c${activeGlowBorder}\\bord4}${fullTokens[k]}{\\rQuranMain}`);
          } else {
            formattedParts.push(fullTokens[k]);
          }
        }

        const lineText = formattedParts.join(' ') + ayahBracket;
        lines.push(`Dialogue: 1,${startStr},${endStr},QuranMain,,0,0,0,,${lineText}`);
      }

      // Post-verse pause: Show full neutral verse until ayahEndSec
      const lastWord = ayahWords[ayahWords.length - 1];
      const lastWordEnd = (lastWord.endMs ?? lastWord.startMs + 600) / 1000;
      if (ayahEndSec > lastWordEnd + 0.05) {
        const startStr = formatAssTimestamp(lastWordEnd);
        const endStr = formatAssTimestamp(ayahEndSec);
        const fullText = fullTokens.join(' ') + ayahBracket;
        lines.push(`Dialogue: 1,${startStr},${endStr},QuranMain,,0,0,0,,${fullText}`);
      }
    }
  }

  return lines.join('\n');
}

/**
 * Executes Idea 1: Pure Native FFmpeg + ASS Filtergraph video render.
 * Renders high-quality Quran reel in 2-5 seconds with zero Chromium footprint!
 */
export async function renderFfmpegAssVideo(
  options: DeterministicRenderOptions
): Promise<DeterministicRenderResult> {
  // Engine 1 keeps its own quota and dispatch identity, while the canonical
  // browser harness guarantees that no visible setting is dropped.
  return renderFullFidelityVideo(options, { label: 'Engine 1 FFmpeg', preset: 'veryfast' });

  const { manifest, outputPath, signal, onProgress } = options;

  const ffmpegPath = getFfmpegBinary();
  if (!ffmpegPath || (path.isAbsolute(ffmpegPath) && !fs.existsSync(ffmpegPath))) {
    throw new Error('Native FFmpeg executable is missing on server.');
  }

  const randomId = crypto.randomBytes(8).toString('hex');
  const scratchDir = path.join(os.tmpdir(), `render_ass_${randomId}`);
  await fs.promises.mkdir(scratchDir, { recursive: true });

  let ffmpegProc: any = null;

  try {
    onProgress?.(5, 0, 0, 'تجهيز المقطع الصوتي والخلفية...');
    const audioTrackPath = await prepareAudioTrack(manifest, scratchDir);
    await prepareBackgroundAsset(manifest, scratchDir);

    if (signal?.aborted) {
      throw new Error('Render cancelled by user.');
    }

    // Measure audio duration
    if (!manifest.audio.durationSeconds || manifest.audio.durationSeconds <= 0) {
      const audioProbe = await probeMediaFile(audioTrackPath);
      if (audioProbe.durationSeconds > 0) {
        manifest.audio.durationSeconds = audioProbe.durationSeconds;
      }
    }

    const { width, height } = manifest.outputDimensions;
    const fps = manifest.fps || 30;
    const totalFrames = Math.max(1, Math.ceil(manifest.audio.durationSeconds * fps));
    const audioBitrate = manifest.audioBitrate || '192k';

    // 1. Generate ASS Subtitle File
    onProgress?.(15, 0, 0, 'توليد ملف الترجمة والتشكيل القرآني (ASS)...');
    const fontsDir = path.resolve(process.cwd(), 'server/assets/fonts');
    const assContent = generateQuranAssContent(manifest, fontsDir);
    const assFilePath = path.join(scratchDir, 'subtitles.ass');
    await fs.promises.writeFile(assFilePath, assContent, 'utf8');

    // 2. Resolve Background Input
    const bg = manifest.background;
    let bgInputArgs: string[] = [];
    const isVideoBg = bg.type === 'video';

    // Escaped ASS path for FFmpeg filtergraph (Windows backslashes must be forward slashes)
    const escapedAssPath = assFilePath.replace(/\\/g, '/').replace(/:/g, '\\:');
    const escapedFontsDir = fontsDir.replace(/\\/g, '/').replace(/:/g, '\\:');

    // Video filter: Scale background, add dynamic dark overlay for high contrast, and overlay ASS subtitles
    const overlayAlpha = typeof manifest.background?.overlayOpacity === 'number'
      ? Math.max(0.0, Math.min(0.95, manifest.background.overlayOpacity))
      : 0.42;
    const filterComplex = `[0:v]scale=${width}:${height}:force_original_aspect_ratio=increase,crop=${width}:${height},drawbox=x=0:y=0:w=iw:h=ih:color=black@${overlayAlpha.toFixed(2)}:t=fill,ass='${escapedAssPath}':fontsdir='${escapedFontsDir}',fps=${fps}[v]`;

    let bgSourceFile = bg.url;
    // If background was prepared into scratch directory
    const matchedPrepared = fs.readdirSync(scratchDir).find((f) => f.startsWith('bg_source'));
    if (matchedPrepared) {
      bgSourceFile = path.join(scratchDir, matchedPrepared);
    }

    if (isVideoBg && fs.existsSync(bgSourceFile)) {
      bgInputArgs = ['-stream_loop', '-1', '-i', bgSourceFile];
    } else if (fs.existsSync(bgSourceFile)) {
      bgInputArgs = ['-loop', '1', '-i', bgSourceFile];
    } else {
      // Fallback or explicit solid elegant background if source file not on disk
      const solidColor = (bg.type === 'color' && bg.url && bg.url.startsWith('#')) ? bg.url : '#0B1519';
      bgInputArgs = [
        '-f', 'lavfi',
        '-i', `color=c=${solidColor}:s=${width}x${height}:r=${fps}`,
      ];
    }

    // 3. Assemble FFmpeg Command
    onProgress?.(25, 0, totalFrames, 'بدء الريندر الصاروخي عبر FFmpeg ASS...');
    const ffmpegArgs = [
      '-y',
      ...getFfmpegResourceArgs(),
      ...bgInputArgs,
      '-i', audioTrackPath,
      '-filter_complex', filterComplex,
      '-map', '[v]',
      '-map', '1:a',
      '-c:v', 'libx264',
      ...getFfmpegVideoEncoderArgs(),
      '-preset', getFfmpegPreset('veryfast'),
      '-crf', '19',
      '-pix_fmt', 'yuv420p',
      '-c:a', 'aac',
      '-b:a', audioBitrate,
      '-ar', '44100',
      '-ac', '2',
      '-shortest',
      '-movflags', '+faststart',
      outputPath,
    ];

    logger.info(`Starting FFmpeg ASS render [${randomId}]: ${width}x${height} @ ${fps}fps`);

    await new Promise<void>((resolve, reject) => {
      ffmpegProc = spawn(ffmpegPath, ffmpegArgs, { windowsHide: true });
      let stderr = '';

      const onAbort = () => {
        try {
          if (ffmpegProc && !ffmpegProc.killed) {
            ffmpegProc.kill('SIGKILL');
          }
        } catch {
          // FFmpeg may have exited between the state check and kill call.
        }
      };

      if (signal) {
        if (signal.aborted) {
          onAbort();
          try {
            if (fs.existsSync(outputPath)) fs.unlinkSync(outputPath);
          } catch {
            // The output may not exist yet or may still be held by FFmpeg.
          }
          reject(new Error('Render cancelled by user (تم إلغاء عملية الريندر).'));
          return;
        }
        signal.addEventListener('abort', onAbort, { once: true });
      }

      ffmpegProc.stderr.on('data', (d: Buffer) => {
        const text = d.toString();
        stderr += text;
        const timeMatch = text.match(/time=(\d+):(\d+):(\d+\.\d+)/);
        if (timeMatch) {
          const hours = parseInt(timeMatch[1], 10);
          const mins = parseInt(timeMatch[2], 10);
          const secs = parseFloat(timeMatch[3]);
          const currentSeconds = hours * 3600 + mins * 60 + secs;
          const pct = Math.min(95, Math.round(25 + (currentSeconds / manifest.audio.durationSeconds) * 70));
          const currentFrame = Math.round(currentSeconds * fps);
          onProgress?.(pct, currentFrame, totalFrames, 'معالجة وتشكيل إطارات الفيديو...');
        }
      });

      ffmpegProc.on('close', async (code: number | null, exitSignal: NodeJS.Signals | null) => {
        if (signal) signal.removeEventListener('abort', onAbort);
        if (signal?.aborted) {
          for (let i = 0; i < 15; i++) {
            try {
              if (fs.existsSync(outputPath)) {
                fs.unlinkSync(outputPath);
              }
              break;
            } catch {
              await new Promise((r) => setTimeout(r, 40));
            }
          }
          reject(new Error('Render cancelled by user (تم إلغاء عملية الريندر).'));
          return;
        }
        if (code === 0) {
          resolve();
        } else {
          const termination = code === null ? `signal ${exitSignal || 'unknown'}` : `code ${code}`;
          reject(new Error(`FFmpeg ASS Render failed [${termination}]: ${stderr.slice(-1200)}`));
        }
      });

      ffmpegProc.on('error', (err: any) => {
        if (signal) signal.removeEventListener('abort', onAbort);
        reject(new Error(`Failed to spawn FFmpeg ASS engine: ${err.message}`));
      });
    });

    if (signal?.aborted) {
      throw new Error('Render cancelled by user (تم إلغاء عملية الريندر).');
    }

    onProgress?.(98, totalFrames, totalFrames, 'التحقق من سلامة الفيديو النهائي...');

    // 4. Validate Output with ffprobe
    const probe = await probeMediaFile(outputPath);
    const validation = validateProbeAgainstSpec(probe, fps);
    if (!validation.valid) {
      throw new Error(`Rendered ASS video failed probe validation: ${validation.errors.join(', ')}`);
    }

    const stat = await fs.promises.stat(outputPath);
    logger.info(`✅ FFmpeg ASS Render [${randomId}] completed successfully: ${(stat.size / 1024 / 1024).toFixed(2)} MB`);

    return {
      outputPath,
      fileSizeBytes: stat.size,
      durationSeconds: probe.durationSeconds,
      totalFrames,
      probe,
    };
  } catch (err) {
    if (signal?.aborted || (err instanceof Error && /cancel|abort|الغاء/i.test(err.message))) {
      for (let i = 0; i < 15; i++) {
        try {
          if (fs.existsSync(outputPath)) {
            fs.unlinkSync(outputPath);
          }
          break;
        } catch {
          await new Promise((r) => setTimeout(r, 40));
        }
      }
    }
    throw err;
  } finally {
    try {
      if (fs.existsSync(scratchDir)) {
        await fs.promises.rm(scratchDir, { recursive: true, force: true });
      }
    } catch (e: any) {
      logger.warn('Failed cleaning scratchDir for ASS render:', e.message);
    }
  }
}
